### ISSUE TITLE
`rip` command needs better regex

### ISSUE THREAD

**Issue by SamStudio8** [zuzakistan/civilservant#141]
Initially implemented after #58, the `rip` response could probably do with looking for delimited rips only

**Comment by SamStudio8** [comment]
so it goes

**Comment by zuzak** [comment]
but the "so it goes" after every mention of javascript is absolutely hilarious every time

**Comment by SamStudio8** [comment]
is it though

**Comment by SamStudio8** [comment]
how about `(rip\b|javascript)`
