### ISSUE TITLE
Countdown onload happens too quickly on bot start

### ISSUE THREAD

**Issue by zuzak** [zuzakistan/civilservant#151]
The bot will try sending a `PRIVMSG` as soon as `countdown.js` is loaded.
This seems to trip freenode's anti-spam procedures and cause the bot to crash.

We should delay the initial poll somehow. We could do it by just upping the timeout, but other ways might be better. For example:
* starting the timer once for each channel on join (requires #150)
* starting the timer only once a successful connection is received (after a `900` message from the server)

**Comment by georgewatson** [comment]
What if we don't trigger the count if `lastTick` is undefined?

**Comment by zuzak** [comment]
All you'd be doing is making the the first `PRIVMSG` occur after 1000-odd milliseconds from start.

That'd probably fix the issue for now, but it's not very robust -- what if there's a bad network connection and the connection to IRC takes three seconds to complete?
