### ISSUE TITLE
randomly owo

### ISSUE THREAD

**Issue by kragniz** [zuzakistan/civilservant#166]
I would like the news ticker to owo responses infrequently.

**Comment by SamStudio8** [comment]
i suppose proposition-#161 could make this happen quite easily by doing an if rand() in whatever hook owo registered with news

**Comment by zuzak** [comment]
this is almost implemented by #156 
all that needs doing is replacing that boolean on-off switch with a probability

**Comment by zuzak** [comment]
fixed in #212
