### ISSUE TITLE
A50 counter is off by one unit

### ISSUE THREAD

**Issue by zuzak** [zuzakistan/civilservant#233]
I think the automatic counter is slightly off.
At the 24 hour mark, it seems to  "23 hours, 59 minutes, and 59 seconds" to "23 hours", which is not correct.

```
22:00:00 UTC -civilservant:##zuzakistan- Article 50 expires in 23 hours
```

**Comment by georgewatson** [comment]
Did f27904d not fix this?

I'll take another look, but I feel like that should have worked.
