### ISSUE TITLE
Remove buttery module

### ISSUE THREAD

**Issue by zuzak** [zuzakistan/civilservant#246]
The buttery.js module is mostly disabled. It is mostly disruptive features that do not add value, and its commands if executed on freenode will cause a k-line.

As we now only use civilservant on freenode, I'm happy removing `buttery.js` and its associated data files entirely.

Fixes #245

**Comment by kragniz** [comment]
no

**Comment by zuzak** [comment]
【﻿ｄｉｓｐｕｔｅｄ】
