### ISSUE TITLE
the !number command has an incorrect helptext

### ISSUE THREAD

**Issue by zuzak** [zuzakistan/civilservant#311]

**Comment by dVp007** [comment]
I want to help how can i help you ?

**Comment by zuzak** [comment]
Hi there,

The problem here is that the helptext for the `!numbers` command, which is defined in [line 5 of modules/numbers.js](https://github.com/zuzakistan/civilservant/blob/master/modules/numbers.js#L5), isn't right. It should say something that describes what the `!numbers` command does, like "Outputs a number in a given language", but at the moment it just says it "asks the bot to greet the channel", which it doesn't do (the helptext has been copied from the `!hello` command).

We need to change line 5 of `modules/numbers.js` to better show what the command does.

**Comment by dVp007** [comment]
can you help me out ? how to connect the chat and how to see the bot's output ? how to actually start contributing to the project

**Comment by dVp007** [comment]
<img width="688" alt="Capture" src="https://user-images.githubusercontent.com/15525172/64488021-fbd0c500-d25f-11e9-8cbe-823a3945d785.PNG">
this is what it shows

**Comment by zuzak** [comment]
Hi there,

The README had an incorrect link and didn't point to the right place.
This meant that you joined a different channel to the bot, so you couldn't see each other.

By default, the IRC bot connects to the ##zuzakistan-lab channel on irc.freenode.net.
You can connect to it via [webchat](https://kiwiirc.com/nextclient/irc.freenode.net/##zuzakistan-lab) or by using [any IRC client](https://en.wikipedia.org/wiki/Comparison_of_Internet_Relay_Chat_clients).

If you want it to connect elsewhere, create a `debug.json` file like this, replacing the values as appropriate, and then start the bot with `NODE_ENV=debug npm start`.
```json
{
  "irc": {
     "server": "irc.freenode.net",
     "channel": "##zuzakistan-lab",
     "nick": "civilservant-48"
  }
}
```
