### ISSUE TITLE
The default configuration should use SSL

### ISSUE THREAD

**Issue by zuzak** [zuzakistan/civilservant#390]
The default IRC connection is `chat.freenode.net:6667`
We should change that to default to connect securely ([RFC 7194](https://tools.ietf.org/html/rfc7194)):
* the `irc.server` configuration variable should still default to `chat.freenode.net`
* the `irc.port` configuration variable should default to `6697` 
* the `irc.secure` configuration variable should default to `true`

**Comment by G-Thompson-Ops** [comment]
Going to try and pick this up

**Comment by zuzak** [comment]
Fixed in #393 

thanks :)
