### ISSUE TITLE
Respond to "rip" or variants

### ISSUE THREAD

**Issue by fxcqz** [zuzakistan/civilservant#58]
Should reply with "so it goes"

**Comment by danhedron** [comment]
+1 missing this functionality is blocking

**Comment by zuzak** [comment]
This just needs another entry in [data/triggers.json](https://github.com/zuzakistan/civilservant/blob/master/data/triggers.json). Feel free to make a pull request.

**Comment by SamStudio8** [comment]
this was a terrible idea, you should all feel bad
