### ISSUE TITLE
An empty watchlist means all edits, not no edits

### ISSUE THREAD

**Issue by zuzak** [zuzakistan/civilservant#7]
Steps to repro:
1. Set `wikipedia.watchlist` to `[]` in config.json
2. Run the bot

What should happen:
1. No edits are reported

What actually happens:
1. Every single edit from every `wikipedia.channels` wiki is reported in real time
2. The bot floods off the server

Workaround:
1. Add an impossible page name as a thing to watch (see [WP:NCHASHTAG](https://en.wikipedia.org/wiki/WP:NCHASHTAG)). Pick something unlikely to be in an edit summary as well (255 `#`s would do the trick).

**Comment by zuzak** [comment]
This happens due to the hacky regex constructed in `wikimediarc.js`. Instead of a regex of `/foo|bar/`, we get a regex of `//`, which matches everything.

**Comment by kragniz** [comment]
:skull:
