### ISSUE TITLE
Remove marco module

### ISSUE THREAD

**Issue by zuzak** [zuzakistan/civilservant#87]
The marco.js module was added so we could track progress of an order for a local takeaway in Aberystwyth. It's one of the worst coded modules in civilservant, and the takeaway in question has ceased trading.

We should remove the module.

**Comment by SamStudio8** [comment]
rip

**Comment by danhedron** [comment]
The functionality should be preserved with a 🍕 command that orders a dominoes pizza to the speaker's address.

E.g. https://github.com/RIAEvangelist/node-dominos-pizza-api
